const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),bcrypt=require('bcryptjs');
const work=path.resolve(__dirname,'../work');fs.mkdirSync(work,{recursive:true});process.env.HALL_DATA_DIR=fs.mkdtempSync(path.join(work,'business-'));process.env.HALL_UPLOAD_DIR=path.join(process.env.HALL_DATA_DIR,'uploads');process.env.HALL_DEMO='1';
const app=require('../server'),db=require('../server/db');const password='Business-Test-2026!';db.prepare('UPDATE users SET password=?,must_change=0').run(bcrypt.hashSync(password,4));
test('Business lifecycle and failure boundaries',async t=>{
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const call=async(url,token,body,method)=>{const response=await fetch(base+'/api'+url,{method:method||(body?'POST':'GET'),headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return{status:response.status,data:await response.json().catch(()=>null)};};
 try{
 const teacher=(await call('/auth/login',null,{username:'teacher',password})).data.token,student=(await call('/auth/login',null,{username:'student',password})).data.token;
 const qbody={type:'single',stem:'Lifecycle question',options:['yes','no'],answer:'A',score:2,published:true};
 const makeQuiz=async(type='single')=>{const q=(await call('/resources/questions',teacher,{...qbody,type,answer:type==='essay'?'':qbody.answer})).data;const quiz=(await call('/resources/quizzes',teacher,{title:'Lifecycle quiz',description:'test',time_minutes:1,question_ids:[q.id],published:true})).data;return{q,quiz};};
 await t.test('invalid choice answer cannot be published',async()=>{assert.equal((await call('/resources/questions',teacher,{...qbody,answer:'Z'})).status,400);assert.equal((await call('/resources/questions',teacher,{...qbody,type:'judge',answer:'maybe'})).status,400);});
 await t.test('question used by a live quiz cannot be silently archived',async()=>{const {q,quiz}=await makeQuiz();assert.equal((await call('/resources/questions/'+q.id,teacher,null,'DELETE')).status,409);assert.equal((await call('/resources/quizzes/'+quiz.id+'/start',student,{})).status,200);});
 await t.test('started attempt remains submittable after resource withdrawal',async()=>{const {q,quiz}=await makeQuiz();const a=(await call('/resources/quizzes/'+quiz.id+'/start',student,{})).data;await call('/resources/quizzes/'+quiz.id,teacher,null,'DELETE');const r=await call('/resources/quizzes/'+quiz.id+'/attempt',student,{attemptId:a.attemptId,answers:{[q.id]:'A'}});assert.equal(r.status,200);assert.equal(r.data.score,2);});
 await t.test('deadline uses saved draft without a 30 second editing grace',async()=>{const {q,quiz}=await makeQuiz();const a=(await call('/resources/quizzes/'+quiz.id+'/start',student,{})).data;assert.equal((await call('/resources/attempts/'+a.attemptId+'/draft',student,{answers:{[q.id]:'B'}},'PUT')).status,200);db.prepare('UPDATE quiz_attempts SET deadline=? WHERE id=?').run(new Date(Date.now()-1000).toISOString(),a.attemptId);const r=await call('/resources/quizzes/'+quiz.id+'/attempt',student,{attemptId:a.attemptId,answers:{[q.id]:'A'}});assert.equal(r.data.score,0);assert.equal(r.data.usedSavedDraft,true);});
 await t.test('teacher can correct an already marked essay with audit',async()=>{const {q,quiz}=await makeQuiz('essay');const a=(await call('/resources/quizzes/'+quiz.id+'/start',student,{})).data;await call('/resources/quizzes/'+quiz.id+'/attempt',student,{attemptId:a.attemptId,answers:{[q.id]:'essay'}});assert.equal((await call('/resources/attempts/'+a.attemptId+'/grade',teacher,{scores:{[q.id]:1},feedback:'first'})).status,200);assert.equal((await call('/resources/attempts/'+a.attemptId+'/grade',teacher,{scores:{[q.id]:2},feedback:'correction'})).status,200);assert.equal(db.prepare('SELECT score FROM quiz_attempts WHERE id=?').get(a.attemptId).score,2);});
 await t.test('task progress is snapshotted and invalid booleans rejected',async()=>{const p=(await call('/resources/projects/1',student)).data;const progress=p.tasks.map(()=>true);assert.equal((await call('/resources/projects/1/progress',student,{progress:progress.map(()=> 'false')},'PUT')).status,400);await call('/resources/projects/1/progress',student,{progress},'PUT');const sub=(await call('/resources/projects/1/submit',student,{content:'v1 report',files:[]})).data;assert.deepEqual(JSON.parse(db.prepare('SELECT task_progress FROM project_submissions WHERE id=?').get(sub.id).task_progress),progress);});
 await t.test('peer work freezes the report and cannot be duplicated',async()=>{const sub=(await call('/resources/projects/2/submit',student,{content:'original evidence',files:[]})).data;const payload={item_type:'project',title:'Versioned work',summary:'evidence summary',submission_id:sub.id,rubric_id:2};const first=await call('/peer/items',student,payload);assert.equal(first.status,200);const replay=await call('/peer/items',student,payload);assert.equal(replay.data.id,first.data.id);await call('/resources/projects/2/submit',student,{content:'revised evidence',files:[]});const detail=(await call('/peer/items/'+first.data.id,student)).data;assert.equal(detail.evidence.content,'original evidence');assert.equal(detail.evidence.version,1);});
 await t.test('returned submission retains feedback and has accessible history',async()=>{const sub=(await call('/resources/projects/3/submit',student,{content:'report',files:[]})).data;assert.equal((await call('/resources/grade-submission/'+sub.id,teacher,{grade:50,feedback:'old grade'})).status,200);assert.equal((await call('/resources/submissions/'+sub.id+'/reopen',teacher,{reason:'Please add uncertainty'})).status,200);const detail=(await call('/resources/projects/3',student)).data;assert.equal(detail.mine.feedback,'Please add uncertainty');const history=await call('/resources/submissions/'+sub.id+'/versions',student);assert.equal(history.status,200);assert(history.data.some(v=>v.payload.grade===50));});
 await t.test('an upload that is not video cannot be used as a recording',async()=>{const data=new FormData();data.append('file',new Blob(['test']),'not-video.txt');const file=await(await fetch(base+'/api/upload',{method:'POST',headers:{Authorization:'Bearer '+student},body:data})).json();const sub=(await call('/resources/projects/4/submit',student,{content:'report',files:[]})).data;assert.equal((await call('/peer/items',student,{item_type:'project',title:'not video',summary:'x',submission_id:sub.id,rubric_id:2,recording:file.url})).status,400);});
 await t.test('transfer does not leak assigned works from previous class',async()=>{const peer=db.prepare("SELECT id,name,student_no,avatar FROM users WHERE username='li'").get();const other=(await call('/auth/login',null,{username:'li',password})).data.token;const oldItems=(await call('/peer/items',other)).data;const cls=(await call('/teacher/classes',teacher,{name:'Transfer class',code:'transfer'})).data;await call('/teacher/students/'+peer.id,teacher,{...peer,class_id:cls.id},'PUT');const fresh=(await call('/auth/login',null,{username:'li',password})).data.token;const after=(await call('/peer/items',fresh)).data;assert.equal(after.length,0);assert(oldItems.length>0);});
 await t.test('manual input cannot retain a false trusted analysis source',async()=>{const r=await call('/workshop/analysis',student,{title:'Bad source',model:'linear',dataset:[{x:1,y:1},{x:2,y:2}],provenance:{session_id:999,manual:false}});assert.notEqual(r.status,200);});
 await t.test('stale teacher report cannot grade a newer submission',async()=>{const sub=(await call('/resources/projects/4/submit',student,{content:'version one',files:[]})).data;const before=db.prepare('SELECT version FROM project_submissions WHERE id=?').get(sub.id);await call('/resources/projects/4/submit',student,{content:'version two',files:[]});assert.equal((await call('/resources/grade-submission/'+sub.id,teacher,{grade:80,feedback:'stale review',version:before.version})).status,409);});
 await t.test('resume owns snapshot and never discloses solutions',async()=>{const {quiz}=await makeQuiz();const a=(await call('/resources/quizzes/'+quiz.id+'/start',student,{})).data;await call('/resources/quizzes/'+quiz.id,teacher,null,'DELETE');const r=await call('/resources/attempts/'+a.attemptId+'/resume',student);assert.equal(r.status,200);assert.equal(r.data.questions[0].answer,undefined);assert.equal(r.data.questions[0].analysis,undefined);assert.equal((await call('/resources/attempts/'+a.attemptId+'/resume',teacher)).status,409);});
 await t.test('edited older cleaning record controls the latest effective decision',async()=>{const s=db.prepare("SELECT s.id,m.id measurement_id FROM sim_sessions s JOIN sim_measurements m ON m.session_id=s.id JOIN users u ON u.id=s.student_id WHERE u.username='student' AND m.group_complete=1 LIMIT 1").get();assert(s);const body={session_id:s.id,measurement_id:s.measurement_id,label:'test',point_label:'point',abnormal_code:'MANUAL',cause:'review',action:'verify',resolved:false,decision:'exclude'};const first=(await call('/workshop/cleaning',student,body)).data;await call('/workshop/cleaning',student,{...body,decision:'keep'});db.prepare("UPDATE cleaning_records SET updated_at='2000-01-01' WHERE session_id=?").run(s.id);assert.equal((await call('/workshop/cleaning/'+first.id,student,body,'PUT')).status,200);const points=(await call('/workshop/session-points/'+s.id,student)).data;assert.equal(points.groups.find(g=>g.id===s.measurement_id).decision,'exclude');});
 }finally{await new Promise(r=>server.close(r));db.close();}
});
