const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'../work');fs.mkdirSync(root,{recursive:true});
process.env.HALL_DATA_DIR=fs.mkdtempSync(path.join(root,'test-data-'));
process.env.HALL_UPLOAD_DIR=path.join(process.env.HALL_DATA_DIR,'uploads');process.env.HALL_DEMO='1';process.env.HALL_JWT_SECRET=crypto.randomBytes(48).toString('hex');
const app=require('../server'),db=require('../server/db'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const password='Regression-Test-2026!';db.prepare('UPDATE users SET password=?,must_change=0').run(bcrypt.hashSync(password,4));
test('Platform security and teaching regression',async t=>{
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
  const request=async(route,token,body,method)=>{const r=await fetch(base+'/api'+route,{method:method||(body?'POST':'GET'),headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return{status:r.status,data:await r.json().catch(()=>null)};};
  try{
    const teacher=(await request('/auth/login',null,{username:'teacher',password})).data.token;
    const student=(await request('/auth/login',null,{username:'student',password})).data.token;
    const other=(await request('/auth/login',null,{username:'li',password})).data.token;
    await t.test('old key and nonexistent users rejected',async()=>{assert.equal((await request('/teacher/dashboard',jwt.sign({id:1,role:'teacher'},'hall-teaching-platform-secret-2026'))).status,401);assert.equal((await request('/teacher/dashboard',jwt.sign({id:9999,version:1},process.env.HALL_JWT_SECRET))).status,401);assert.equal((await request('/teacher/dashboard',student)).status,403);assert.equal((await request('/teacher/dashboard',teacher)).status,200);});
    await t.test('sensitive fields and registration restricted',async()=>{const users=await request('/teacher/students',teacher);assert.equal(users.status,200);assert.equal(Object.hasOwn(users.data[0],'password'),false);assert.equal((await request('/auth/register',null,{username:'bad',password})).status,403);});
    await t.test('question and B-paper grading',async()=>{assert.equal((await request('/resources/questions',student)).status,403);const qs=(await request('/resources/questions',teacher)).data;assert(qs.every(q=>typeof q.score==='number'));const started=await request('/resources/quizzes/2/start',student,{});assert.equal(started.status,200);assert(started.data.questions.every(q=>!Object.hasOwn(q,'answer')));const answers=Object.fromEntries(qs.map(q=>[q.id,q.type==='multiple'?q.answer.split(''):q.answer]));const response=await request('/resources/quizzes/2/attempt',student,{attemptId:started.data.attemptId,answers});assert.equal(response.status,200);assert.equal(response.data.score,response.data.total);assert.equal(response.data.detail.find(d=>d.id===18).correct,true);const replay=await request('/resources/quizzes/2/attempt',student,{attemptId:started.data.attemptId,answers});assert.equal(replay.data.attemptId,response.data.attemptId);});
    const session=(await request('/sim/start',student,{})).data.platformSessionId;
    const events=[1,2,3,4].map((slot,i)=>({eventId:'test:'+slot,sessionId:'test-unity',type:'OnMeasureData',measurement:{groupId:'test-group',slot,isDirection:[1,1,-1,-1][i],imDirection:[1,-1,-1,1][i],voltageDirection:1,IS_mA:3,IM_A:.4,B_T:.2,rawVoltage_mV:[1,-1,1,-1][i],groupComplete:slot===4}}));
    await t.test('session ownership and atomic replay',async()=>{assert.equal((await request('/sim/events',other,{platformSessionId:session,events})).status,403);assert.equal((await request('/sim/events',student,{platformSessionId:session,events})).status,200);assert.equal((await request('/sim/events',student,{platformSessionId:session,events})).status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM sim_measurements WHERE session_id=?').get(session).n,4);const bad=[{...events[0],eventId:'new-valid'}, {...events[1],eventId:'new-invalid',measurement:{...events[1].measurement,slot:1.5}}];assert.equal((await request('/sim/events',student,{platformSessionId:session,events:bad})).status,400);assert.equal(db.prepare('SELECT COUNT(*) n FROM sim_events WHERE event_id=?').get('new-valid').n,0);const finish={eventId:'test:finish',sessionId:'test-unity',type:'OnExperimentComplete'};assert.equal((await request('/sim/events',student,{platformSessionId:session,events:[finish]})).status,200);assert.equal((await request('/sim/events',student,{platformSessionId:session,events:[finish]})).status,200);});
    await t.test('cleaning excludes correct measurement and validates owner',async()=>{const points=(await request('/workshop/session-points/'+session,student)).data.groups;const saved=await request('/workshop/cleaning',student,{session_id:session,measurement_id:points[0].id,decision:'exclude',cause:'复测',action:'等待复测',resolved:false,abnormal_code:'MANUAL'});assert.equal(saved.status,200);assert.equal((await request('/workshop/session-points/'+session,student)).data.groups[0].decision,'exclude');assert.equal((await request('/workshop/cleaning',other,{session_id:session,cause:'x',action:'x'})).status,403);});
    await t.test('project validation and grading lifecycle',async()=>{assert.equal((await request('/resources/projects/999/submit',student,{content:'report'})).status,404);const sub=await request('/resources/projects/2/submit',student,{content:'完整实验报告',files:[]});assert.equal(sub.status,200);assert.equal((await request('/resources/grade-submission/'+sub.data.id,teacher,{grade:0,feedback:'请补充证据'})).status,200);assert.equal((await request('/resources/projects/2',student)).data.mine.grade,0);assert.equal((await request('/resources/projects/2/submit',student,{content:'overwrite',files:[]})).status,409);assert.equal((await request('/resources/submissions/'+sub.data.id+'/reopen',teacher,{reason:'允许补充'})).status,200);assert.equal((await request('/resources/projects/2/submit',student,{content:'补充报告',files:[]})).status,200);assert(db.prepare('SELECT COUNT(*) n FROM submission_versions').get().n>0);});
    await t.test('review range, dimensions and appeal lock',async()=>{const rubric=(await request('/peer/rubrics',student)).data.find(r=>r.target_type==='experiment');const item=await request('/peer/items',student,{item_type:'experiment',title:'实验',summary:'四方向测量摘要',session_id:session,rubric_id:rubric.id});assert.equal(item.status,200);const scores=Object.fromEntries(rubric.dimensions.map(d=>[d.name,d.max]));assert.equal((await request('/peer/items/'+item.data.id+'/review',other,{rubric_id:rubric.id,scores:{...scores,[rubric.dimensions[0].name]:999},comment:'证据'})).status,400);assert.equal((await request('/peer/items/'+item.data.id+'/review',other,{rubric_id:rubric.id,scores:{...scores,[rubric.dimensions[0].name]:'25'},comment:'证据'})).status,400);const rv=await request('/peer/items/'+item.data.id+'/review',other,{rubric_id:rubric.id,scores,comment:'证据充分'});assert.equal(rv.status,200);const appeal=await request('/peer/appeals',student,{ref_type:'review',ref_id:rv.data.id,content:'请求复核'});assert.equal(appeal.status,200);assert.equal((await request('/peer/items/'+item.data.id+'/review',other,{rubric_id:rubric.id,scores,comment:'修改'})).status,409);assert.equal((await request('/peer/appeals/'+appeal.data.id+'/reply',teacher,{reply:'核对后撤销',decision:'void'})).status,200);const grades=(await request('/teacher/grades',teacher)).data;assert(grades.every(g=>g.total>=0&&g.total<=100));});
    await t.test('uploads require safe types and authorized downloads',async()=>{
      const upload=async(name,content)=>{const form=new FormData();form.append('file',new Blob([content]),name);return fetch(base+'/api/upload',{method:'POST',headers:{Authorization:'Bearer '+student},body:form});};
      assert.equal((await upload('bad.html','<html>')).status,400);assert.equal((await upload('fake.pdf','<html>')).status,400);
      const r=await upload('report.txt','report');assert.equal(r.status,200);const f=await r.json();assert.equal((await fetch(base+f.url)).status,401);assert.equal((await fetch(base+f.url,{headers:{Authorization:'Bearer '+other}})).status,403);const good=await fetch(base+f.url,{headers:{Authorization:'Bearer '+student}});assert.equal(good.status,200);assert.match(good.headers.get('content-disposition'),/attachment/);
    });
    await t.test('expired unsubmitted attempts do not disclose answers',async()=>{const a=(await request('/resources/quizzes/1/start',student,{})).data;db.prepare('UPDATE quiz_attempts SET deadline=? WHERE id=?').run('2000-01-01T00:00:00Z',a.attemptId);assert.equal((await request('/resources/quizzes/1/start',student,{})).status,200);const attempts=(await request('/resources/attempts',student)).data;const expired=attempts.find(x=>x.id===a.attemptId);assert.equal(expired.status,'expired');assert.equal(Object.hasOwn(expired,'snapshot'),false);assert.equal(Object.hasOwn(expired,'detail'),false);});
    await t.test('legacy works preserve bound rubric and reviewer assignment',async()=>{const old=db.prepare("INSERT INTO review_items(student_id,item_type,title,summary) VALUES(2,'experiment','legacy','existing report')").run().lastInsertRowid;db.prepare('DELETE FROM migrations WHERE version=143').run();require('../server/legacy-review-migration')(db);assert.equal(db.prepare('SELECT rubric_id FROM review_items WHERE id=?').get(old).rubric_id,1);assert(db.prepare('SELECT COUNT(*) n FROM review_assignments WHERE item_id=?').get(old).n>0);});
    await t.test('password reset revokes previous token and preserves spaces',async()=>{const spaced=' Leading-Space-123! ';assert.equal((await request('/teacher/students/3/reset-password',teacher,{password:spaced})).status,200);assert.equal((await request('/me',other)).status,401);assert.equal((await request('/auth/login',null,{username:'li',password:spaced})).status,200);assert.equal((await request('/auth/login',null,{username:'li',password:spaced.trim()})).status,401);});
    await t.test('ungraded work blocks publication; graded snapshots are private',async()=>{assert.equal((await request('/teacher/grades/publish',teacher,{reason:'回归测试发布'})).status,409);const sub=db.prepare('SELECT id FROM project_submissions WHERE student_id=2 AND project_id=2').get();assert.equal((await request('/resources/grade-submission/'+sub.id,teacher,{grade:60,feedback:'补交评阅完成'})).status,200);assert.equal((await request('/teacher/grades/publish',teacher,{reason:'回归测试发布'})).status,200);const r=await request('/grades',student);assert.equal(r.status,200);assert(r.data.every(g=>g.student_id===2));});
  }finally{await new Promise(r=>server.close(r));db.close();}
});
