<template><div class="max-w-6xl space-y-5">
<div class="flex flex-wrap gap-3 border-b pb-3"><button v-for="(label,key) in tabs" :class="tab===key?'btn-primary':'btn-ghost'" @click="tab=key">{{label}}</button></div>
<section v-if="tab==='projects'"><h2 class="font-bold mb-4">课题成果</h2><div v-for="s in submissions" :key="s.id" class="border-b py-4 flex flex-wrap items-center gap-4"><b>{{s.student_name}}</b><span>{{s.project_title}} · v{{s.version}}</span><span>{{s.grade==null?'待评阅':s.grade+'分'}}</span><button class="btn-soft ml-auto" @click="openProject(s)">查看报告</button></div><p v-if="!submissions.length">暂无成果</p></section>
<section v-if="tab==='quizzes'"><h2 class="font-bold mb-4">答卷评阅</h2><div v-for="a in attempts.filter(hasEssay)" :key="a.id" class="border-b py-4 flex flex-wrap gap-4"><b>{{a.student_name}}</b><span>{{a.quiz_title}}</span><span>{{a.status==='pending'?'待阅卷':a.score+'/'+a.total}}</span><button class="btn-soft ml-auto" @click="openQuiz(a)">{{a.status==='pending'?'评阅简答题':'复核简答题'}}</button></div><p v-if="!attempts.some(hasEssay)">暂无简答题答卷</p></section>
<section v-if="tab==='sessions'"><h2 class="font-bold mb-4">实验数据核验</h2><div v-for="s in sessions" :key="s.id" class="border-b py-4 flex flex-wrap gap-4"><b>{{s.student_name}}</b><span>会话 #{{s.id}} · {{s.finished?'已完成':'未完成'}}</span><span>{{s.verified?s.quality_score+'分':'待核验'}}</span><button class="btn-soft ml-auto" @click="openSession(s)">查看证据</button></div></section>
<div v-if="current" class="modal-mask" @click.self="current=null"><div class="modal p-6 max-w-4xl space-y-4">
<div class="flex justify-between"><h2 class="font-bold">{{current.student_name}} · {{current.project_title||current.quiz_title||'实验会话 #'+current.id}}</h2><button @click="current=null" title="关闭"><Icon name="x"/></button></div>
<template v-if="tab==='projects'"><p class="whitespace-pre-wrap break-words">{{current.content}}</p><ProtectedFile v-for="f in current.files" :src="f.url" :name="f.name"/><div v-if="current.grade!=null" class="text-brand-700">当前成绩：{{current.grade}} · {{current.feedback}}</div><details v-for="h in versions" :key="h.id"><summary>历史 v{{h.version}} · {{h.payload.grade==null?'未评':h.payload.grade+'分'}}</summary><p class="whitespace-pre-wrap break-words">{{h.payload.content}}</p><p>{{h.payload.feedback}}</p><ProtectedFile v-for="f in JSON.parse(h.payload.files||'[]')" :src="f.url" :name="f.name"/></details></template>
<template v-if="tab==='quizzes'"><div v-for="d in detail.filter(d=>Object.hasOwn(essayScores,d.id))" :key="d.id" class="border-b py-3"><b>{{d.stem}}</b><p class="whitespace-pre-wrap my-2">{{answers[d.id]||'未作答'}}</p><label>得分 / {{d.max}}<input v-model.number="essayScores[d.id]" type="number" min="0" :max="d.max" class="input"/></label></div></template>
<template v-if="tab==='sessions'"><div class="overflow-auto"><table class="w-full text-sm"><thead><tr><th>组/槽位</th><th>IS/mA</th><th>IM/A</th><th>原始/mV</th><th>VH/mV</th></tr></thead><tbody><tr v-for="m in current.measurements" class="border-b"><td>{{m.group_id}} / {{m.slot}}</td><td>{{m.IS_mA}}</td><td>{{m.IM_A}}</td><td>{{m.raw_mV}}</td><td>{{m.VH_mV}}</td></tr></tbody></table></div><details><summary>操作异常与事件</summary><pre class="text-xs whitespace-pre-wrap break-words">{{JSON.stringify({abnormals:current.abnormals,events:current.events},null,2)}}</pre></details></template>
<label v-if="tab!=='quizzes'" class="block">成绩（0–100）<input v-model.number="score" type="number" min="0" max="100" class="input"/></label>
<label class="block">评阅意见 / 核验依据<textarea v-model="feedback" class="input min-h-24"/></label>
<div class="flex gap-3"><button class="btn-primary" :disabled="saving||(tab==='sessions'&&!current.finished)" @click="save">提交评阅</button><button v-if="tab==='projects'&&current.grade!=null" class="btn-ghost" @click="reopen">退回重交</button></div>
</div></div></div></template>
<script setup>
import {ref,onMounted} from 'vue';import {api} from '../../api';import Icon from '../../components/Icon.vue';import ProtectedFile from '../../components/ProtectedFile.vue';
const tabs={projects:'课题评阅',quizzes:'简答题阅卷',sessions:'实验核验'},tab=ref('projects'),submissions=ref([]),attempts=ref([]),sessions=ref([]),current=ref(null),score=ref(0),feedback=ref(''),saving=ref(false),detail=ref([]),answers=ref({}),essayScores=ref({});
const versions=ref([]);
async function openProject(s){versions.value=[];const rows=await api('/resources/submissions/'+s.id+'/versions');current.value=s;versions.value=rows;score.value=s.grade??0;feedback.value=s.feedback||'';}
function hasEssay(a){return ['pending','graded'].includes(a.status)&&JSON.parse(a.snapshot||'[]').some(q=>q.type==='essay');}
function openQuiz(a){current.value=a;detail.value=JSON.parse(a.detail);answers.value=JSON.parse(a.answers);const ids=new Set(JSON.parse(a.snapshot||'[]').filter(q=>q.type==='essay').map(q=>q.id));essayScores.value=Object.fromEntries(detail.value.filter(d=>ids.has(d.id)).map(d=>[d.id,d.score||0]));feedback.value=detail.value.find(d=>ids.has(d.id))?.feedback||'';}
async function openSession(s){current.value={...s,...await api('/sim/sessions/'+s.id)};score.value=s.quality_score??0;feedback.value='';}
async function save(){if(saving.value)return;saving.value=true;try{if(tab.value==='projects')await api('/resources/grade-submission/'+current.value.id,{method:'POST',body:{grade:score.value,feedback:feedback.value,version:current.value.version}});else if(tab.value==='quizzes')await api('/resources/attempts/'+current.value.id+'/grade',{method:'POST',body:{scores:essayScores.value,feedback:feedback.value}});else await api('/teacher/sessions/'+current.value.id+'/verify',{method:'POST',body:{score:score.value,reason:feedback.value}});current.value=null;await load();}finally{saving.value=false;}}
async function reopen(){if(!feedback.value)return alert('请填写退回理由');await api('/resources/submissions/'+current.value.id+'/reopen',{method:'POST',body:{reason:feedback.value}});current.value=null;await load();}
async function load(){submissions.value=await api('/resources/submissions');attempts.value=await api('/resources/attempts');sessions.value=await api('/teacher/sessions');}onMounted(load);
</script>
